name: (ES) m1-disenar-api

on:
  workflow_dispatch:

jobs:
  claat:
    runs-on: ubuntu-latest
    steps:
      - name: Download Source Code (git)
        uses: actions/checkout@v2

      - name: Generate Code Labs Content
        uses: ./.github/actions/claat
        with:
          client-id: ${{ secrets.clientId }}
          client-secret: ${{ secrets.clientSecret }}
          refresh-token: ${{ secrets.refreshToken }}          
          doc-id: 1FpxUEBtJNzb1olvGlfGNRbeBPBp2UKPsAuespv7oZyY