name: (ES) es-m2-documente-api

on:
  workflow_dispatch:

jobs:
  claat:
    runs-on: ubuntu-latest
    steps:
      - name: Download Source Code (git)
        uses: actions/checkout@v2
        with:
          ref: dev
            
      - name: Generate Code Labs Content
        uses: ./.github/actions/claat
        with:
          client-id: ${{ secrets.clientId }}
          client-secret: ${{ secrets.clientSecret }}
          refresh-token: ${{ secrets.refreshToken }}          
          doc-id: 1rlEnzCpzrHmOqBYiaAwBadIglE5wyNLs_gr4rdlUVN0